menu:
- {name: 'cv', url: '/assets/cv.pdf'}
- {name: 'publications', url: '/publications'}
- {name: 'photography', url: '/photography'}
- {name: '<i class="fas fa-home"></i>', url: '/'}


social:
- {icon: 'github', link: 'https://github.com/KaanSirin', type: 'b'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/kaan-şirin-5732462ba/', type: 'b'}
- {icon: 'envelope', link: 'mailto:kaan.sirin@sabanciuniv.edu', type: 'r'}
